name: pocketdad
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.1
  firebase_auth: ^4.14.0
  firebase_core: ^2.22.0
  firebase_ui_auth: ^1.10.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.4
  form_builder_validators: ^9.1.0
  multi_select_flutter: ^4.1.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.2.1
  intl: ^0.18.1
  flutter_dotenv: ^5.1.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  custom_lint:
  riverpod_generator: ^3.0.0-dev.4
  riverpod_lint: ^2.3.1
  json_serializable: ^6.7.1
  freezed: ^2.4.5

flutter:
  uses-material-design: true

  fonts:
    - family: Chakra Petch
      fonts:
        - asset: fonts/Chakra_Petch/ChakraPetch-Bold.ttf
    - family: Mulish
      fonts:
        - asset: fonts/Mulish/static/Mulish-Bold.ttf
        - asset: fonts/Mulish/static/Mulish-Italic.ttf
  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - .env
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/initialData/
