name: pocketdad
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.4
  form_builder_validators: ^9.1.0
  multi_select_flutter: ^4.1.3
  riverpod_annotation: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner:
  custom_lint:
  riverpod_generator: ^3.0.0-dev.4
  riverpod_lint: ^2.3.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

  fonts:
    - family: Chakra Petch
      fonts:
        - asset: fonts/Chakra_Petch/ChakraPetch-Regular.ttf
        - asset: fonts/Chakra_Petch/ChakraPetch-SemiBold.ttf
    - family: Mulish
      fonts:
        - asset: fonts/Mulish/static/Mulish-LightItalic.ttf
        - asset: fonts/Mulish/static/Mulish-Light.ttf
        - asset: fonts/Mulish/static/Mulish-Italic.ttf
        - asset: fonts/Mulish/static/Mulish-Medium.ttf
        - asset: fonts/Mulish/static/Mulish-Regular.ttf
        - asset: fonts/Mulish/static/Mulish-SemiBold.ttf